// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hskbneuxcujrobyjrhxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhza2JuZXV4Y3Vqcm9ieWpyaHh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMDIxMTMsImV4cCI6MjA1NDU3ODExM30.PDdheh8yguiJPeNubZ_jCNepMU3cCHYF80jZk5xCusw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);